### ISSUE TITLE
Add sassc formula

### ISSUE THREAD

**Issue by nex3** [sass/homebrew-sass#1]
It would be nice to have a `sassc` formula here so that users can easily install that on Mac. Probably one of the LibSass maintainers should do this, since they know the build system better than I do.

**Comment by xzyfer** [comment]
I'm not sure what the correct semantic are for brew, or casks. SassC already has a brew formula in core - https://github.com/Homebrew/homebrew-core/pull/22785

Does it make sense to also have it here?

**Comment by nex3** [comment]
Ah, probably not.
