### ISSUE TITLE
Can't install due to Dart error

### ISSUE THREAD

**Issue by itzsaga** [sass/homebrew-sass#12]
Currently running `brew install sass/sass/sass` returns the following:

```bash
brew install sass/sass/sass
==> Installing sass from sass/sass
Error: dart-lang/dart/dart: undefined method `prefer_64_bit?' for OS::Mac:Module
```

**Comment by am11** [comment]
Issue was reported upstream few hours ago: https://github.com/dart-lang/homebrew-dart/issues/58.

**Comment by itzsaga** [comment]
The upstream issue is now fixed.
