### ISSUE TITLE
brew install sass/sass/sass failed 

### ISSUE THREAD

**Issue by ikamal** [sass/homebrew-sass#15]
2019-07-10 11:36:46 +0800
  
/usr/local/opt/dart/bin/pub
get

Resolving dependencies...
Invalid request method

HOMEBREW_VERSION: 2.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b83463091513826127c14acae81a7c354dfce69
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 36018e96a13d13998d559c77b7226b9e6aa3e7d0
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/xxx/Library/Caches/Homebrew
HOMEBREW_LOGS: /Users/xxx/Library/Logs/Homebrew
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: N/A
CLT headers: 10.2.1.0.1.1554506761

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/dart/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by nex3** [comment]
Does this reproduce consistently? It looks like it could be a transient server error.

**Comment by samhwang** [comment]
I can confirm this is still reproducible today. Running homebrew version 2.1.15 and ruby version 2.5.1.

I just noticed the command homebrew was trying to run. Should there be a space between `-D` and `version=1.23.1` ?

The command in question: `/usr/local/opt/dart/bin/dart2aot -Dversion=1.23.1 bin/sass.dart sass.dart.native`.

Homebrew output:
```bash
$ brew upgrade sass
==> Upgrading 1 outdated package:
sass/sass/sass 1.23.0 -> 1.23.1
==> Upgrading sass/sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.23.1.tar.gz
Already downloaded: /Users/***/Library/Caches/Homebrew/downloads/f473f9345e5f93149201f18f2aadef0d778fcaf39a953cc4a19b43bb73a8b558--dart-sass-1.23.1.tar.gz
==> /usr/local/opt/dart/bin/pub get
==> /usr/local/opt/dart/bin/dart2aot -Dversion=1.23.1 bin/sass.dart sass.dart.native
Last 15 lines from /Users/***/Library/Logs/Homebrew/sass/02.dart2aot:
2019-10-25 13:15:54 +1100

/usr/local/opt/dart/bin/dart2aot
-Dversion=1.23.1
bin/sass.dart
sass.dart.native

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues

These open issues may also help:
brew install sass/sass/sass failed  https://github.com/sass/homebrew-sass/issues/15
```

**Comment by tracytn0411** [comment]
I got the same problem updating Sass as well.  Tried uninstall then install, but it does not work.
MacOS Catalina 10.15.1
Brew 2.1.15

Steps to reproduce:

```bash
$ brew -v
Homebrew 2.1.15
Homebrew/homebrew-core (git revision 179da2; last commit 2019-10-30)
Homebrew/homebrew-cask (git revision 53b61; last commit 2019-10-30)
$ brew install sass/sass/sass
==> Installing sass from sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.23.1.tar.gz
Already downloaded: /Users/tracy/Library/Caches/Homebrew/downloads/f473f9345e5f93149201f18f2aadef0d778fcaf39a953cc4a19b43bb73a8b558--dart-sass-1.23.1.tar.gz
==> /usr/local/opt/dart/bin/pub get
==> /usr/local/opt/dart/bin/dart2aot -Dversion=1.23.1 bin/sass.dart sass.dart.native
Last 15 lines from /Users/tracy/Library/Logs/Homebrew/sass/02.dart2aot:
2019-10-30 11:36:55 -0700

/usr/local/opt/dart/bin/dart2aot
-Dversion=1.23.1
bin/sass.dart
sass.dart.native

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues

These open issues may also help:
brew install sass/sass/sass failed  https://github.com/sass/homebrew-sass/issues/15
```

**Comment by FlyboyArt** [comment]
Same for me.. 

MacOS Catalina 10.15.1, Brew 2.1.16, Dart 2.6.0 (installed via Brew), sass 1.2.23 (trying to install via Brew).

**Comment by ostoh** [comment]
I am getting the same problem too.

MacOS Mojave 10.14.6

Output: 

```
$ brew -v
Homebrew 2.1.16
Homebrew/homebrew-core (git revision 2f417; last commit 2019-11-05)
$ brew install sass/sass/sass
Updating Homebrew...
==> Installing sass from sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.23.3.tar.gz
Already downloaded: /Users/austinemaina/Library/Caches/Homebrew/downloads/f2a1c65c05a47b73f76bb02e6cb5f792143c37d4ac464a95ec096fa0ced6196a--dart-sass-1.23.3.tar.gz
==> /usr/local/opt/dart/bin/pub get
==> /usr/local/opt/dart/bin/dart2aot -Dversion=1.23.3 bin/sass.dart sass.dart.na
Last 15 lines from /Users/austinemaina/Library/Logs/Homebrew/sass/02.dart2aot:
2019-11-05 16:04:44 +0300

/usr/local/opt/dart/bin/dart2aot
-Dversion=1.23.3
bin/sass.dart
sass.dart.native


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues

These open issues may also help:
brew install sass/sass/sass failed  https://github.com/sass/homebrew-sass/issues/15
```

**Comment by blackbret94** [comment]
I am also experiencing this issue on macOS Mojave 10.14.5.  Same output as ostoh.

**Comment by eljay040** [comment]
+1 – same as ostoh

**Comment by ciduarte** [comment]
+1, same as ostoh

**Comment by JeremyKeusters** [comment]
Same issue here.

Specs:
- MacOS 10.15.1
- Homebrew 2.1.16
- Ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

Output:
```
jeremy@MBP-van-Jeremy ~ % brew install sass/sass/sass
==> Installing sass from sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.23.3.tar.gz
Already downloaded: /Users/jeremy/Library/Caches/Homebrew/downloads/f2a1c65c05a47b73f76bb02e6cb5f792143c37d4ac464a95ec096fa0ced6196a--dart-sass-1.23.3.tar.gz
==> /usr/local/opt/dart/bin/pub get
==> /usr/local/opt/dart/bin/dart2aot -Dversion=1.23.3 bin/sass.dart sass.dart.na
Last 15 lines from /Users/jeremy/Library/Logs/Homebrew/sass/02.dart2aot:
2019-11-05 22:01:52 +0100

/usr/local/opt/dart/bin/dart2aot
-Dversion=1.23.3
bin/sass.dart
sass.dart.native
```

**Comment by thie1210** [comment]
Had the same problem. Installed via dart2native branch and everything seems fine.

**Comment by cee-r** [comment]
> Had the same problem. Installed via dart2native branch and everything seems fine.

How do you install via that branch?

**Comment by thie1210** [comment]
> How do you install via that branch?

You no longer need to do that since the branch has been merged. But for your information, you point brew to the branch version of the formula—see command below.

`brew install https://raw.githubusercontent.com/sass/homebrew-sass/dart2native/sass.rb`

**Comment by JeremyKeusters** [comment]
Can confirm that the install works again. Thanks for the fix!
