### ISSUE TITLE
 Can't access Sass from Terminal

### ISSUE THREAD

**Issue by renatognunes** [sass/homebrew-sass#17]
I've installed Sass with Brew, but when I try: `sass --version` or `sass --help`

I get this error:

```
Usage: /usr/local/Cellar/dart/2.4.1/libexec/bin/dart2aot [options] <dart-source-file> <dart-aot-file>

Dart AOT (ahead-of-time) compile Dart source code into native machine code.
```
Although, when I look at my homebrew list of packages, I do see Sass. 
I'm using a MacPro with Mojave.

Any help is really helpful here :)

Thanks!

**Comment by nex3** [comment]
Sorry about that! I pushed a change to build a more efficient executable on 64-bit systems, but it was slightly broken. It should be fixed now if you delete it and re-install.

**Comment by renatognunes** [comment]
Hi @nex3 , thank you for the support.
Although, now I'm getting a different error when running sass `--version`:
```
/usr/local/bin/sass: line 2: /usr/local/Cellar/sass/1.22.9/lib/dart2aot: No such file or directory
/usr/local/bin/sass: line 2: exec: /usr/local/Cellar/sass/1.22.9/lib/dart2aot: cannot exe
cute: No such file or directory

**Comment by renatognunes** [comment]
I fixed the issue by changing the file in /usr/local/bin/sass

from:
`exec "/usr/local/Cellar/sass/1.22.9/lib/dart2aot"`
to: 
`exec "/usr/local/Cellar/sass/1.22.9/lib/dartaotruntime"`
