### ISSUE TITLE
'dart pub get' raised 'Invalid request method' error.

### ISSUE THREAD

**Issue by kevinojt** [sass/homebrew-sass#33]
Got follow message while installing:

==> /usr/local/opt/dart/bin/pub get
Last 15 lines from /Users/oujt/Library/Logs/Homebrew/sass/01.pub:
2020-05-08 14:46:43 +0800

/usr/local/opt/dart/bin/pub
get

Resolving dependencies...
Invalid request method

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues

----------------------------------------

Full text of 01.pub
-----------------------------------------
2020-05-08 14:46:43 +0800

/usr/local/opt/dart/bin/pub
get

Resolving dependencies...
Invalid request method

HOMEBREW_VERSION: 2.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1f3b0b971dccb72780b2ef33fafde158cb3909e
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 93a125322e2af6a55de0a0244c14e6bd54145c7d
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
https_proxy: socks5://127.0.0.1:2048
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14, 11.0.6, 1.8.0_172, 1.7.0_79
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/dart/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by jkrems** [comment]
Just to verify: Was this after running `brew install sass/sass/sass`?

**Comment by jathak** [comment]
This might be a flake from `pub get`. Can you try re-running the install command to see if it works?

**Comment by kevinojt** [comment]
I have sass@1.26.3 and dart@2.7.2 installed.
- brew upgrade sass\sass\sass. 
- brew uninstall dart@2.8.1 and sass@1.26.3, brew install sass/sass/sass. 
- Install dart 2.7.2, brew install sass/sass/sass.
- With or without proxy. I'm in China. The GFW may block some sites. So I have to use  proxy. Have same message.
- Try this in two Macs. 
All have same message.

brew install
-------------------------------------------------
==> Upgrading sass/sass/sass 1.26.3 -> 1.26.5
==> Downloading https://github.com/sass/dart-sass/archive/1.26.5.tar.gz
Already downloaded: /Users/oujt/Library/Caches/Homebrew/downloads/464496fff3aa31d011052460ab794f3bb49f9c28e2242efe2359d46a23e7873c--dart-sass-1.26.5.tar.gz
==> /usr/local/opt/dart/bin/pub get
Last 15 lines from /Users/oujt/Library/Logs/Homebrew/sass/01.pub:
2020-05-09 10:02:50 +0800

/usr/local/opt/dart/bin/pub
get

Resolving dependencies...
Invalid request method

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sass/homebrew-sass/issues

**Comment by kevinojt** [comment]
It was network issue. The GFW blocked https://pub.dartlang.org. 

Sorry for wasting your time.

-----------------------------------

==> /usr/local/opt/dart/bin/pub get -v
FINE: Pub 2.8.1
MSG : Resolving dependencies...
SLVR: fact: sass is 1.26.5
SLVR: derived: sass
SLVR: fact: sass depends on args ^1.4.0
SLVR: fact: sass depends on async >=1.10.0 <3.0.0
SLVR: fact: sass depends on charcode ^1.1.0
SLVR: fact: sass depends on cli_repl >=0.1.3 <0.3.0
SLVR: fact: sass depends on collection ^1.8.0
SLVR: fact: sass depends on meta ^1.1.7
SLVR: fact: sass depends on package_resolver ^1.0.0
SLVR: fact: sass depends on path ^1.6.0
SLVR: fact: sass depends on source_maps ^0.10.5
SLVR: fact: sass depends on source_span ^1.6.0
SLVR: fact: sass depends on stack_trace >=0.9.0 <2.0.0
SLVR: fact: sass depends on stream_transform >=0.0.20 <2.0.0
SLVR: fact: sass depends on string_scanner >=0.1.5 <2.0.0
SLVR: fact: sass depends on term_glyph ^1.0.0
SLVR: fact: sass depends on tuple ^1.0.0
SLVR: fact: sass depends on watcher ^0.9.6
SLVR: fact: sass depends on archive >=1.0.0 <3.0.0
SLVR: fact: sass depends on analyzer >=0.37.0 <0.40.0
SLVR: fact: sass depends on cli_pkg ^1.0.0-beta.6
SLVR: fact: sass depends on crypto >=0.9.2 <3.0.0
SLVR: fact: sass depends on dart_style ^1.2.0
SLVR: fact: sass depends on grinder ^0.8.0
SLVR: fact: sass depends on js ^0.6.0
SLVR: fact: sass depends on node_preamble ^1.1.0
SLVR: fact: sass depends on pedantic ^1.0.0
SLVR: fact: sass depends on pub_semver ^1.0.0
SLVR: fact: sass depends on source_span ^1.5.2
SLVR: fact: sass depends on stream_channel >=1.0.0 <3.0.0
SLVR: fact: sass depends on test_descriptor ^1.1.0
SLVR: fact: sass depends on test_process ^1.0.0-rc.1
SLVR: fact: sass depends on test >=0.12.42 <2.0.0
SLVR: fact: sass depends on yaml ^2.0.0
SLVR:   selecting sass
SLVR:   derived: yaml ^2.0.0
SLVR:   derived: test >=0.12.42 <2.0.0
SLVR:   derived: test_process ^1.0.0-rc.1
SLVR:   derived: test_descriptor ^1.1.0
SLVR:   derived: stream_channel >=1.0.0 <3.0.0
SLVR:   derived: source_span ^1.5.2
SLVR:   derived: pub_semver ^1.0.0
SLVR:   derived: pedantic ^1.0.0
SLVR:   derived: node_preamble ^1.1.0
SLVR:   derived: js ^0.6.0
SLVR:   derived: grinder ^0.8.0
SLVR:   derived: dart_style ^1.2.0
SLVR:   derived: crypto >=0.9.2 <3.0.0
SLVR:   derived: cli_pkg ^1.0.0-beta.6
SLVR:   derived: analyzer >=0.37.0 <0.40.0
SLVR:   derived: archive >=1.0.0 <3.0.0
SLVR:   derived: watcher ^0.9.6
SLVR:   derived: tuple ^1.0.0
SLVR:   derived: term_glyph ^1.0.0
SLVR:   derived: string_scanner >=0.1.5 <2.0.0
SLVR:   derived: stream_transform >=0.0.20 <2.0.0
SLVR:   derived: stack_trace >=0.9.0 <2.0.0
SLVR:   derived: source_span ^1.6.0
SLVR:   derived: source_maps ^0.10.5
SLVR:   derived: path ^1.6.0
SLVR:   derived: package_resolver ^1.0.0
SLVR:   derived: meta ^1.1.7
SLVR:   derived: collection ^1.8.0
SLVR:   derived: cli_repl >=0.1.3 <0.3.0
SLVR:   derived: charcode ^1.1.0
SLVR:   derived: async >=1.10.0 <3.0.0
SLVR:   derived: args ^1.4.0
IO  : Get versions from https://pub.dartlang.org/api/packages/args.
IO  : Get versions from https://pub.dartlang.org/api/packages/async.
IO  : Get versions from https://pub.dartlang.org/api/packages/charcode.
IO  : Get versions from https://pub.dartlang.org/api/packages/cli_repl.
IO  : Get versions from https://pub.dartlang.org/api/packages/collection.
IO  : Get versions from https://pub.dartlang.org/api/packages/meta.
IO  : Get versions from https://pub.dartlang.org/api/packages/package_resolver.
IO  : Get versions from https://pub.dartlang.org/api/packages/path.
IO  : Get versions from https://pub.dartlang.org/api/packages/source_maps.
IO  : Get versions from https://pub.dartlang.org/api/packages/stack_trace.
IO  : HTTP GET https://pub.dartlang.org/api/packages/args
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/async
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/charcode
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/cli_repl
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/collection
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/meta
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/package_resolver
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/path
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/source_maps
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/stack_trace
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/stream_transform.
IO  : HTTP GET https://pub.dartlang.org/api/packages/stream_transform
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/string_scanner.
IO  : HTTP GET https://pub.dartlang.org/api/packages/string_scanner
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/term_glyph.
IO  : HTTP GET https://pub.dartlang.org/api/packages/term_glyph
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/tuple.
IO  : HTTP GET https://pub.dartlang.org/api/packages/tuple
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/watcher.
IO  : HTTP GET https://pub.dartlang.org/api/packages/watcher
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/archive.
IO  : HTTP GET https://pub.dartlang.org/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/analyzer.
IO  : HTTP GET https://pub.dartlang.org/api/packages/analyzer
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/cli_pkg.
IO  : HTTP GET https://pub.dartlang.org/api/packages/cli_pkg
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/crypto.
IO  : HTTP GET https://pub.dartlang.org/api/packages/crypto
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/dart_style.
IO  : HTTP GET https://pub.dartlang.org/api/packages/dart_style
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/grinder.
IO  : HTTP GET https://pub.dartlang.org/api/packages/grinder
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/js.
IO  : HTTP GET https://pub.dartlang.org/api/packages/js
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/node_preamble.
IO  : HTTP GET https://pub.dartlang.org/api/packages/node_preamble
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/pedantic.
IO  : HTTP GET https://pub.dartlang.org/api/packages/pedantic
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/pub_semver.
IO  : HTTP GET https://pub.dartlang.org/api/packages/pub_semver
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/source_span.
IO  : HTTP GET https://pub.dartlang.org/api/packages/source_span
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/stream_channel.
IO  : HTTP GET https://pub.dartlang.org/api/packages/stream_channel
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/test_descriptor.
IO  : HTTP GET https://pub.dartlang.org/api/packages/test_descriptor
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/test_process.
IO  : HTTP GET https://pub.dartlang.org/api/packages/test_process
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/test.
IO  : HTTP GET https://pub.dartlang.org/api/packages/test
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
IO  : Get versions from https://pub.dartlang.org/api/packages/yaml.
IO  : HTTP GET https://pub.dartlang.org/api/packages/yaml
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 38DD2EA9-AF15-42C0-9455-B823A4C628CE
    | X-Pub-Environment: homebrew:sass
    | X-Pub-Reason: dev
    | user-agent: Dart pub 2.8.1
SLVR: Version solving took 0:00:00.331032 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.340s).
ERR : Invalid request method
FINE: Exception type: ClientException
FINE: package:pub/src/source/hosted.dart 437:7    BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 188:7    BoundHostedSource._fetchVersions
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 113:52           captureErrors.wrappedCallback
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 126:11           captureErrors
    | package:pub/src/command_runner.dart 191:13  PubCommandRunner.runCommand
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
/usr/local/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
BuildError: Failed executing: /usr/local/opt/dart/bin/pub get -v
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1

...

**Comment by jathak** [comment]
This looks like an issue in either Pub or the proxy you're using, not the Homebrew formula.

Can you try downloading the [dart-sass source](https://github.com/sass/dart-sass) and then running `pub get` within that directory?

**Comment by kevinojt** [comment]
> This looks like an issue in either Pub or the proxy you're using, not the Homebrew formula.
> 
> Can you try downloading the [dart-sass source](https://github.com/sass/dart-sass) and then running `pub get` within that directory?

Yes, it is network issue NOT the Homebrew formula. The GFW blocked https://pub.dartlang.org. I have to install sass with proxy. Dart throws 'Invalid request method' while parsing HTTP data.

**Comment by kevinojt** [comment]
If you are in China and 'dart pub' do not work with your proxy you can use a Pub mirror.
1. Open '/usr/local/Homebrew/Library/Taps/sass/homebrew-sass/sass.rb'
2. Add Pub mirror url environment variable PUB_HOSTED_URL
```
 # Tell the pub server where these installations are coming from.
 ENV["PUB_ENVIRONMENT"] = "homebrew:sass"
 ENV["PUB_HOSTED_URL"] = "https://mirrors.tuna.tsinghua.edu.cn/dart-pub"
```
Read https://flutter.cn/community/china for further info. But you must add pub mirror to sass.rb NOT by 'export'.
