### ISSUE TITLE
Failed install (macOS Catalina)

### ISSUE THREAD

**Issue by chrisfinazzo** [sass/homebrew-sass#34]
<img width="585" alt="Screen Shot 2021-06-17 at 12 04 18 AM" src="https://user-images.githubusercontent.com/1534882/122329526-93684a80-ceff-11eb-90b8-80fcc6cc87a5.png">

Output of `brew config` is as follows:

    HOMEBREW_VERSION: 3.1.12-77-g903b4d4
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 903b4d44c4ef34846d3350524e16e955b1a95a7d
    Last commit: 48 minutes ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 338328ef72930c390ddab4fed390350410893b43
    Core tap last commit: 4 hours ago
    Core tap branch: master
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CASK_OPTS: []
    HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.P6dAf4aIAQ/org.xquartz:0
    HOMEBREW_EDITOR: /usr/local/bin/bbedit
    HOMEBREW_MAKE_JOBS: 8
    Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
    CPU: octa-core 64-bit icelake
    Clang: 12.0.0 build 1200
    Git: 2.32.0 => /usr/local/bin/git
    Curl: 7.64.1 => /usr/bin/curl
    macOS: 10.15.7-x86_64
    CLT: 12.0.0.32.29
    Xcode: 12.4

**Comment by fgm** [comment]
Same error, `brew config`:
```
HOMEBREW_VERSION: 3.1.12-85-g1cb0f0f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1cb0f0fbf22c9f43e47646302dba1debd7bc76f8
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2eaad22fa094d94863f384cc860de0f59cdc56eb
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by chrisfinazzo** [comment]
@fgm, Good to know it's not just me. I actually went through the entire process of uninstalling and reinstalling Homebrew (and my Brewfile) - this is the one piece that's left to do.

Honestly, compared to the gem they used to have, dart/node-sass is a P.I.T.A as it seems like it is under such active development so often that you won't notice it's broken until you're 5 versions behind, start to upgrade and _then_ find out something is broken in the most recent release.

Frustrating.

**Comment by nex3** [comment]
I'm not sure what's going on here... we haven't changed any infrastructure relating to the Homebrew script recently, and while it could be an issue with Dart's script, [these are the only non-automated changes](https://github.com/dart-lang/homebrew-dart/compare/72ab2f95a4673bf5913b012aad2032bb56d82459...991b22a3945a4eb015ba61f383ad35f945ccef95) in months and I don't see anything there that looks related to this error. I'm going to try to spin up a Mac OS dev environment to see if I can reproduce this locally.

> Honestly, compared to the gem they used to have, dart/node-sass is a P.I.T.A as it seems like it is under such active development so often that you won't notice it's broken until you're 5 versions behind, start to upgrade and then find out something is broken in the most recent release.

If we don't make updates, people get mad that the project's dead... if we do make updates, people get mad that it's under active development! Some days you just can't win.

**Comment by mistydemeo** [comment]
This is a Homebrew bug. I've submitted a workaround in #35, but it will get fixed in Homebrew sometime soon.

**Comment by nex3** [comment]
Thanks so much, @mistydemeo!

**Comment by chrisfinazzo** [comment]
> I'm not sure what's going on here... we haven't changed any infrastructure relating to the Homebrew script recently, and while it could be an issue with Dart's script, [these are the only non-automated changes](https://github.com/dart-lang/homebrew-dart/compare/72ab2f95a4673bf5913b012aad2032bb56d82459...991b22a3945a4eb015ba61f383ad35f945ccef95) in months and I don't see anything there that looks related to this error. I'm going to try to spin up a Mac OS dev environment to see if I can reproduce this locally.
> 
> > Honestly, compared to the gem they used to have, dart/node-sass is a P.I.T.A as it seems like it is under such active development so often that you won't notice it's broken until you're 5 versions behind, start to upgrade and then find out something is broken in the most recent release.
> 
> If we don't make updates, people get mad that the project seems dead... if we do make updates, people get mad that it's under active development! Some days you just can't win.

👋 @nex3, thanks for clarifying.

When I came across this, it was in the context of verifying a formula audit that didn't resolve and it simply didn't register with me that the problem was in fact elsewhere.
