### ISSUE TITLE
Brew installation doesn't work with Monterey/Xcode13.2

### ISSUE THREAD

**Issue by isherifwilson** [sass/homebrew-sass#39]
Sass install doesn't seem happy with the location of my command line tools (which seem to be more recent than the ones it is request). Any advice would be great!

(For context, I have dozens of other packages installed using brew all of which are happy so this seems like a sass thing?

```
~ % brew install sass/sass/sass

(TRIMMED)

==> Installing sass from sass/sass
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.
```

Xcode shows the following for installation locations:
<img width="942" alt="Screen Shot 2021-12-15 at 11 31 03 PM" src="https://user-images.githubusercontent.com/2531845/146313839-a02c461e-aa9a-4be4-8286-9b7d0615cd63.png">

Xcode version (13.2):
<img width="642" alt="Screen Shot 2021-12-15 at 11 33 45 PM" src="https://user-images.githubusercontent.com/2531845/146314016-c5238d28-a1f5-49fc-8229-8be5a72e3862.png">

OS: Monterey 12.1
<img width="698" alt="Screen Shot 2021-12-15 at 11 34 37 PM" src="https://user-images.githubusercontent.com/2531845/146314117-d44a1bcf-434d-4aac-be6f-2b77932358ce.png">

**Comment by nex3** [comment]
Sass doesn't invoke anything specific around OS X command-line tools. I suspect this is either a Homebrew issue (unlikely if other Homebrew packages are installing correctly), or an issue with the [Dart homebrew package](https://github.com/dart-lang/homebrew-dart) that Sass depends on.
