### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by huanyichuang** [sass/homebrew-sass#4]
The information below was shown after I used the pub --trace get command

Could not find a file named "pubspec.yaml" in "/usr/local/Cellar/dart/1.24.3/bin".
---- Log transcript ----
FINE: Pub 1.24.3
ERR : Could not find a file named "pubspec.yaml" in "/usr/local/Cellar/dart/1.24.3/bin".
FINE: Exception type: FileException
FINE: package:pub/src/pubspec.dart 419                           new Pubspec.load
    | package:pub/src/package.dart 138                           new Package.load
    | package:pub/src/entrypoint.dart 146                        new Entrypoint
    | package:pub/src/command.dart 42                            PubCommand.entrypoint
    | package:pub/src/command/get.dart 38                        GetCommand.run
    | package:args/command_runner.dart 194                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                    PubCommandRunner.run
    | /Users/whesse/dart/sdk/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                 _Completer.completeError
    | package:args/command_runner.dart 195                       CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                 new Future.microtask
    | package:args/command_runner.dart 142                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand.<fn>
    | dart:async                                                 new Future.sync
    | package:pub/src/utils.dart 102                             captureErrors.<fn>
    | package:stack_trace                                        Chain.capture
    | package:pub/src/utils.dart 117                             captureErrors
    | package:pub/src/command_runner.dart 168                    PubCommandRunner.runCommand
---- End log transcript ----

**Comment by nex3** [comment]
Can you provide some more details? What Homebrew command produced this error? What's the full output of that command?
