### ISSUE TITLE
Because sass requires SDK version >=3.0.0 <4.0.0, version solving failed.

### ISSUE THREAD

**Issue by pocketarc** [sass/homebrew-sass#55]
> Resolving dependencies...
> The current Dart SDK version is 2.18.7.
> 
> Because sass requires SDK version >=3.0.0 <4.0.0, version solving failed.

This is on an M1 MBP. If I `brew remove dart` and then try again, it won't matter, as it will just redownload the wrong version as a dependency of sass.

Is this just me?

```
==> Upgrading 1 outdated package:
sass/sass/sass 1.62.1 -> 1.63.4
==> Fetching dependencies for sass/sass/sass: dart-lang/dart/dart
==> Fetching dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.7/sdk/dartsdk-macos-arm64-release.zip
Already downloaded: /Users/bruno/Library/Caches/Homebrew/downloads/7ef40112c3a051ef146055a37131886c3cbbce2c304aa413140da5fdd4d7d374--dartsdk-macos-arm64-release.zip
==> Fetching sass/sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.63.4.tar.gz
Already downloaded: /Users/bruno/Library/Caches/Homebrew/downloads/349d9140216b45601cec2dafdbca0a54069a86eaee21d734acfb51ef5cd37c77--dart-sass-1.63.4.tar.gz
==> Upgrading sass/sass/sass
  1.62.1 -> 1.63.4 

==> Installing dependencies for sass/sass/sass: dart-lang/dart/dart
==> Installing sass/sass/sass dependency: dart-lang/dart/dart
🍺  /opt/homebrew/Cellar/dart/2.18.7: 920 files, 469.2MB, built in 6 seconds
==> Installing sass/sass/sass
==> /opt/homebrew/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/bruno/Library/Logs/Homebrew/sass/01.dart:
2023-06-20 09:54:39 +0000

/opt/homebrew/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 2.18.7.

Because sass requires SDK version >=3.0.0 <4.0.0, version solving failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/sass/homebrew-sass/issues

```

**Comment by nex3** [comment]
It's entirely unclear to me why this is happening. The [dart-lang/homebrew-dart repo](https://github.com/dart-lang/homebrew-dart/blob/main/Formula/dart.rb) declares its current stable version as 3.0.5, so it's not at all clear why you're getting 2.18.7, especially after you've removed an existing Dart version. This might be something we need to talk to Homebrew folks about.

**Comment by jathak** [comment]
There seems to be some sort of issue with the Dart tap becoming out of date. This seems to have fixed it on my machine:
```
brew tap --repair
brew remove dart
brew update
brew install dart-lang/dart/dart
brew install sass/sass/sass
```

(not sure how much of that is actually necessary, but running through all of them got it working).

We should also change to using the built-in Dart homebrew formula now that it exists, but not sure if that's actually the root cause here.

**Comment by nex3** [comment]
I've filed https://github.com/orgs/Homebrew/discussions/4584 to ask about the proper way to handle this. In the meantime, @pocketarc:

* What's the output of `brew config`, `brew doctor`, and `git -C $(brew --repo tap_org/tap_repo) show` on your system?
* Does `brew update dart` resolve the issue?

**Comment by nex3** [comment]
According to [this answer](https://github.com/orgs/Homebrew/discussions/4584#discussioncomment-6236081) and [the FAQ](https://docs.brew.sh/FAQ#how-do-i-update-my-local-packages), it's apparently required that you run `brew update` before updating or installing new versions of existing taps.

**Comment by pocketarc** [comment]
@nex3 @jathak Thank you so much for the help! It was an out of date tap; the tap couldn't update because the `master` branch got renamed to `main` and my homebrew wasn't getting updates for it. 

`brew tap --repair` solved it!
