### ISSUE TITLE
Because sass requires SDK version >=3.0.0 <4.0.0, version solving failed.

### ISSUE THREAD

**Issue by chiahao** [sass/homebrew-sass#56]
I've already uninstall dart, dart-sdk, and then install sass:
How to fix this?

%> brew install sass/sass/sass
==> Fetching dependencies for sass/sass/sass: dart-lang/dart/dart
==> Fetching dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.7/sdk/dartsdk-macos-arm64-relea
Already downloaded: /Users/chiahao/Library/Caches/Homebrew/downloads/7ef40112c3a051ef146055a37131886c3cbbce2c304aa413140da5fdd4d7d374--dartsdk-macos-arm64-release.zip
==> Fetching sass/sass/sass
==> Downloading https://github.com/sass/dart-sass/archive/1.69.5.tar.gz
Already downloaded: /Users/chiahao/Library/Caches/Homebrew/downloads/6298f4906c8ed136c755afb1b6c2cc3d1860fc4e8e525760f0235cae2d680cc4--dart-sass-1.69.5.tar.gz
==> Installing sass from sass/sass
==> Installing dependencies for sass/sass/sass: dart-lang/dart/dart
==> Installing sass/sass/sass dependency: dart-lang/dart/dart
🍺  /opt/homebrew/Cellar/dart/2.18.7: 920 files, 469.2MB, built in 5 seconds
==> Installing sass/sass/sass
==> /opt/homebrew/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/chiahao/Library/Logs/Homebrew/sass/01.dart:
2023-11-03 15:53:26 +0000

/opt/homebrew/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 2.18.7.

Because sass requires SDK version >=3.0.0 <4.0.0, version solving failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/sass/homebrew-sass/issues

**Comment by nex3** [comment]
For some reason, this is installing Dart 2.18.7, which is extremely outdated. I have no idea why Homebrew would install that version—we just depend on `dart-lang/dart/dart`, which [currently installs](https://github.com/dart-lang/homebrew-dart/blob/main/Formula/dart.rb) Dart 3.3.0. My best guess is that you have a very old version cached somewhere, but I'm not sure the best way to clear Homebrew caches.

**Comment by chiahao** [comment]
But I've already cleanup the cache by `brew cleanup --prune=all`,
Still no luck.
Any help?

**Comment by chiahao** [comment]
%> brew info --json sass
show the dependencies:

```
"build_dependencies": [
      "buf",
      "dart-lang/dart/dart"
    ],
```

%>brew info --json dart-lang/dart/dart
will show:

```
"urls": {
      "stable": {
        "url": "https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.7/sdk/dartsdk-macos-arm64-release.zip",
        "tag": null,
        "revision": null,
        "using": null,
        "checksum": "2742114776a5b476f64cb96596eaeb2d346f65686b7f358b06de83f0e3eb2a48"
      },
      "head": {
        "url": "https://storage.googleapis.com/dart-archive/channels/dev/release/3.0.0-114.0.dev/sdk/dartsdk-macos-arm64-release.zip",
        "branch": null,
        "using": null
      }
    },
```

where could I request this? thanks.

**Comment by jmooring** [comment]
This is a Homebrew problem, not a Sass problem. I suggest you raise your question here:
<https://github.com/orgs/Homebrew/discussions>

This issue is closed.
