### ISSUE TITLE
Cannot install on MacOS Arm64 (m3) b/c Dart SDK <3.0

### ISSUE THREAD

**Issue by marshalloram** [sass/homebrew-sass#59]
I can't get this to install b/c of the Dart SDK dependency of > 3.0. Mac OS only installs 2.18.3 via homebrew, even though the main Dart SDK channel offers 3.4.0 for MacOS Arm64. How do I get that version installed to support homebrew-sass? 

Of is it simply not possible on a Mac?

**Comment by ntkme** [comment]
The dart lang formula is currently at 3.3.1: https://github.com/dart-lang/homebrew-dart/blob/main/Formula/dart.rb

Try running `brew upgrade` first?

**Comment by H6** [comment]
I ended up downloading it directly from https://github.com/sass/dart-sass/releases and adding it to my PATH. brew did not work out because of the dart version conflict.

**Comment by ntkme** [comment]
What's the output of `brew info dart-lang/dart/dart`?

```
$ brew info dart-lang/dart/dart
==> dart-lang/dart/dart: stable 3.3.3, HEAD
SDK
https://dart.dev
Conflicts with:
  dart-beta (because dart-beta ships the same binaries)
/opt/homebrew/Cellar/dart/3.3.3 (987 files, 585.3MB) *
  Built from source on 2024-03-27 at 12:32:35
From: https://github.com/dart-lang/homebrew-dart/blob/HEAD/Formula/dart.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
Please note the path to the Dart SDK:
  /opt/homebrew/opt/dart/libexec
```

Also, if you have `dart-sdk` from homebrew main repo installed, you need to remove that first as it conflicts with `dart-lang/dart/dart`. E.g. `brew rm dart-sdk`

**Comment by marshalloram** [comment]
```
$ brew info dart-lang/dart/dart
==> dart-lang/dart/dart: stable 2.18.3, HEAD
SDK
https://dart.dev
Conflicts with:
  dart-beta (because dart-beta ships the same binaries)
/opt/homebrew/Cellar/dart/2.18.3 (920 files, 469.2MB) *
  Built from source on 2024-03-19 at 08:47:00
From: https://github.com/dart-lang/homebrew-dart/blob/HEAD/Formula/dart.rb
==> Options
--HEAD
Install HEAD version
==> Caveats
Please note the path to the Dart SDK:
  /opt/homebrew/opt/dart/libexec
```

When I try to remove dart-sdk is says 
```
$ brew rm dart-sdk
Error: No such keg: /opt/homebrew/Cellar/dart-sdk
```

**Comment by ntkme** [comment]
Ok, you simply has outdated `dart-lang/dart/dart`, in that case you should just upgrade that:

``` sh
brew upgrade dart-lang/dart/dart
```

**Comment by marshalloram** [comment]
I swear I tried `$brew upgrade` first before starting this thread.... but I just did again and it worked. Thank you and I apologize for wasting your time. Cheers!
