### ISSUE TITLE
SDK Error when trying to upgrade SASS

### ISSUE THREAD

**Issue by ijeremyg** [sass/homebrew-sass#62]
Hi all,

I am getting an error about Dart SDK when trying to upgrade sass.

```
/usr/local/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 2.18.5.

Because sass requires SDK version >=3.0.0 <4.0.0, version solving failed.
```

However, `dart-sdk 3.3.4 already installed`

I have tried to unininstall sass, dart and dart-sdk and restart, but to no avail.

thank you,
Jer

**Comment by nex3** [comment]
You must have Dart 2.18.5 installed _somewhere_, even if not through Homebrew. I don't know if there's anything we can do about this on our end—either it's an issue with your setup, or it's an issue with Homebrew not prioritizing its own dependencies in the PATH during installation.
